# Generated by Django 5.1.7 on 2025-12-18 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_userprofile_email_remove_userprofile_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('beaches', 'Beaches'), ('mountains', 'Mountains'), ('cities', 'Cities'), ('nature', 'Nature')], max_length=20)),
                ('image_url', models.URLField(help_text='Enter image URL from Unsplash or other sources')),
                ('price_per_day', models.DecimalField(decimal_places=2, help_text='Price in INR', max_digits=10)),
                ('duration_days', models.IntegerField(help_text='Recommended duration in days')),
                ('highlights', models.TextField(help_text='Key highlights (comma-separated)')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage slider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
